version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=l1*fmssm0j0ryx%y8#d16pkwqj)=e7@h6%@7ys7owur3s&c_)#
      - DEBUG=1 
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_s34g4ZarBLbWm3HS72ycXLRY00dJedb7Kq
      - STRIPE_TEST_SECRET_KEY=sk_test_IO1q1VuRLroxtXE6EpN9Y1Z800YvnL0VVr
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
